[package]
name = "example_os"
version = "0.1.0"
authors = ["Isaac Woods <isaacwoods.home@gmail.com>",
           "Philipp Oppermann <dev@phil-opp.com>"]

[dependencies]
bit_field = "0.7.0"
bitflags = "0.9.1"
multiboot2 = "0.1.0"
once = "0.3.2"
rlibc = "1.0"
spin = "0.4.5"
volatile = "0.1.0"
x86_64 = "0.1.2"
linked_list_allocator = "0.6.*"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "0.2.1"

[lib]
crate-type = ["staticlib"]
