language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true

branches:
  only:
    # This is where pull requests from "bors r+" are build
    - staging
    # This is where pull requests from "bors try" are build
    - trying
    # This allows building of pull requests
    - master

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo test --features running_on_ci

notifications:
  email: change
