[workspace]
members = ["tools/aml-tester", "tools/acpi-dumper", "tools/aml-test-tools", "tools/uacpi-test-adapter"]
# See the note in the no-alloc-check README.md to see why this is excluded.
exclude = ["tools/no-alloc-check"]
resolver = "2"

[package]
name = "acpi"
version = "6.1.1"
authors = ["Isaac Woods"]
repository = "https://github.com/rust-osdev/acpi"
description = "A pure-Rust library for interacting with ACPI"
categories = ["hardware-support", "no-std"]
license = "MIT/Apache-2.0"
edition = "2024"

[dependencies]
bit_field = "0.10.2"
bitflags = "2.5.0"
lock_api = { version = "0.4.14", optional = true, public = true }
log = "0.4.20"
spinning_top = { version = "0.3.0", optional = true, public = true }
pci_types = { version = "0.10.0", public = true }
byteorder = { version = "1.5.0", optional = true, default-features = false }
smallvec = { version = "1.15.2", optional = true, default-features = false, public = true }

[dev-dependencies]
aml-test-tools = { path = "tools/aml-test-tools" }
lock_api = "0.4.14"
parking_lot = "0.12.5"
pretty_env_logger = "0.5.0"
serial_test = "4.0.1"

[features]
default = ["alloc", "aml"]
alloc = []
aml = [
    "alloc",
    "dep:lock_api",
    "dep:spinning_top",
    "dep:byteorder",
    "dep:smallvec",
]
