//! A collection of helper utilities for testing AML using the [`acpi`] crate.
//!
//! These utilities are very heavily based on the way the [`acpi`] crate has used them historically.
//! As always, feel free to offer PRs for improvements.

pub mod handlers;

use acpi::aml::{AmlError, Interpreter};
use acpi::{
    address::MappedGas,
    aml::{namespace::AmlName, object::Object},
    Handler,
    PhysicalMapping,
};
use log::{error, trace};
use std::{
    ffi::OsStr,
    fs::File,
    io::Read,
    path::PathBuf,
    process::Command,
    ptr::NonNull,
    str::FromStr,
    sync::Arc,
};
use std::io::Write;
use tempfile::{tempdir, NamedTempFile, TempDir};
use crate::handlers::logging_handler::LoggingHandler;

/// Possible results of [`resolve_and_compile`].
pub enum CompilationOutcome {
    /// Not a valid ASL or AML file.
    Ignored,
    /// This file is already an AML file, does not need recompiling.
    IsAml(PathBuf),
    /// Both .asl and .aml files exist, and the .aml file is newer - it does not need recompiling.
    Newer(PathBuf),
    /// There's a .asl file only, but [`resolve_and_compile`] was called with `can_compile=false`.
    NotCompiled(PathBuf),
    /// Compilation was attempted but failed. The compilation output has been printed to stdout.
    Failed(PathBuf),
    /// An ASL file was found and compiled successfully. This variant contains the path to the
    /// compiled AML file.
    Succeeded(PathBuf),
}

/// Possible results of [`run_test_for_file`].
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub enum TestResult {
    /// The test passed.
    Pass,
    /// The test ASL failed compilation by `iasl`.
    CompileFail,
    /// Our interpreter failed to parse the resulting AML.
    ParseFail,
    // TODO: should we do this??
    NotCompiled,
}

/// An internal-only struct that helps keep track of temporary files generated by
/// [`run_test_for_string`]
struct TempScriptFile {
    // This appears to be unused, but since it deletes the temporary directory when it's dropped, we
    // need to keep it.
    #[allow(unused)]
    dir: TempDir,
    asl_file: NamedTempFile,
    aml_file: PathBuf,
}

/// Determine what to do with this file - ignore, compile and parse, or just parse.
/// If ".aml" does not exist, or if ".asl" is newer, compiles the file.
/// If the ".aml" file is newer, indicate it is ready to parse.
///
/// Arguments:
/// - `path`: The filename of an ASL file to (possibly) compile.
/// - `can_compile`: Whether compilation is allowed for this file. If not, any existing AML file
///   with the same name (but different extension) will be used.
pub fn resolve_and_compile(path: &PathBuf, can_compile: bool) -> std::io::Result<CompilationOutcome> {
    // If this file is aml and it exists, it's ready for parsing
    // metadata() will error if the file does not exist
    if path.extension() == Some(OsStr::new("aml")) && path.metadata()?.is_file() {
        return Ok(CompilationOutcome::IsAml(path.clone()));
    }

    // If this file is not asl, it's not interesting. Error if the file does not exist.
    if path.extension() != Some(OsStr::new("asl")) || !path.metadata()?.is_file() {
        return Ok(CompilationOutcome::Ignored);
    }

    let aml_path = path.with_extension("aml");

    if aml_path.is_file() {
        let asl_last_modified = path.metadata()?.modified()?;
        let aml_last_modified = aml_path.metadata()?.modified()?;
        // If the aml is more recent than the asl, use the existing aml
        // Otherwise continue to compilation
        if asl_last_modified <= aml_last_modified {
            return Ok(CompilationOutcome::Newer(aml_path));
        }
    }

    if !can_compile {
        return Ok(CompilationOutcome::NotCompiled(path.clone()));
    }

    // Compile the ASL file using `iasl`
    println!("Compiling file: {}", path.display());
    let output = Command::new("iasl").arg(path).output()?;

    if !output.status.success() {
        println!(
            "Failed to compile ASL file: {}. Output from iasl:\n {}",
            path.display(),
            String::from_utf8_lossy(&output.stderr)
        );
        Ok(CompilationOutcome::Failed(path.clone()))
    } else {
        Ok(CompilationOutcome::Succeeded(aml_path))
    }
}

/// Construct a new [interpreter](Interpreter) to use for testing.
///
/// This interpreter uses some simple fake registers and FACS to facilitate testing. It is not
/// mandatory to use this interpreter for testing when using other functions in this crate.
///
/// Arguments:
///
/// * `handler`: The Handler to be called by the interpreter when needed. This crate includes some
///   example [handlers].
pub fn new_interpreter<T>(handler: T) -> Interpreter<T>
where
    T: Handler + Clone,
{
    let fake_registers = Arc::new(acpi::registers::FixedRegisters {
        pm1_event_registers: acpi::registers::Pm1EventRegisterBlock {
            pm1_event_length: 8,
            pm1a: unsafe {
                MappedGas::map_gas(
                    acpi::address::GenericAddress {
                        address_space: acpi::address::AddressSpace::SystemIo,
                        bit_width: 32,
                        bit_offset: 0,
                        access_size: 1,
                        address: 0x400,
                    },
                    &handler,
                )
                .unwrap()
            },
            pm1b: None,
        },
        pm1_control_registers: acpi::registers::Pm1ControlRegisterBlock {
            pm1a: unsafe {
                MappedGas::map_gas(
                    acpi::address::GenericAddress {
                        address_space: acpi::address::AddressSpace::SystemIo,
                        bit_width: 32,
                        bit_offset: 0,
                        access_size: 1,
                        address: 0x600,
                    },
                    &handler,
                )
                .unwrap()
            },
            pm1b: None,
        },
    });

    // This PhysicalMapping is dropped when the interpreter is dropped, and if you use logging in
    // the handler object you'll see a call to Handler::unmap_physical_region without any
    // corresponding call to Interpreter::map_physical_region.
    let fake_facs = PhysicalMapping {
        physical_start: 0x0,
        virtual_start: NonNull::new(0x8000_0000_0000_0000 as *mut acpi::sdt::facs::Facs).unwrap(),
        region_length: 32,
        mapped_length: 32,
        handler: handler.clone(),
    };
    Interpreter::new(handler, 2, fake_registers, Some(fake_facs))
}

/// Test an AML file using [`run_test`]
///
/// Arguments:
///
/// * `file`: The path to the AML file to test. This must be an AML file otherwise the test will
///   fail very quickly.
/// * `interpreter`: The interpreter to use for testing.
pub fn run_test_for_file(file: &PathBuf, interpreter: &mut Interpreter<impl Handler + Clone>) -> TestResult {
    let Ok(mut file) = File::open(&file) else {
        return TestResult::CompileFail;
    };
    let mut contents = Vec::new();
    file.read_to_end(&mut contents).unwrap();

    const AML_TABLE_HEADER_LENGTH: usize = 36;
    let stream = &contents[AML_TABLE_HEADER_LENGTH..];

    match run_test(stream, interpreter) {
        Ok(()) => TestResult::Pass,
        Err(e) => {
            error!("Error running test: {:?}", e);
            TestResult::ParseFail
        }
    }
}

/// Test an ASL script given as a string, using [`run_test`].
///
/// Arguments:
/// * `asl`: A string slice containing an ASL script. This will be compiled to AML using `iasl` and
///   then tested using [`run_test`]
/// * `handler`: The handler to use for the test
pub fn run_test_for_string(asl: &'static str, handler: impl Handler) {
    let script = create_script_file(asl);
    resolve_and_compile(&script.asl_file.path().to_path_buf(), true).unwrap();

    let logged_handler = LoggingHandler::new(handler);
    let mut interpreter = new_interpreter(logged_handler);

    assert_eq!(run_test_for_file(&script.aml_file, &mut interpreter), TestResult::Pass);
}

/// Internal function to create a temporary script file from an ASL string, plus to calculate the
/// name of the post-compilation AML file.
fn create_script_file(asl: &'static str) -> TempScriptFile {
    let dir = tempdir().unwrap();
    trace!("Created temp dir: {:?}", dir.path());
    let mut script_file = NamedTempFile::with_suffix_in(".asl", &dir).unwrap();
    trace!("Created temp file: {:?}", script_file.path());

    let output_stem = script_file.path().file_stem().unwrap().to_str().unwrap();
    let output_name = format!("{}.aml", output_stem);
    let output_full_name = dir.path().join(output_name.clone());

    let new_asl = asl.replace("%FN%", output_name.as_str());

    script_file.write_all(new_asl.as_bytes()).unwrap();
    script_file.flush().unwrap();

    TempScriptFile { dir, asl_file: script_file, aml_file: output_full_name }
}

/// Run a test on an AML stream.
///
/// In this context, "a test" means:
///
/// * Attempting to parse the AML
/// * If the AML contains a "MAIN" method, attempting to execute it.
///
/// Arguments:
///
/// * `stream`: A slice containing the AML bytecode to test.
/// * `interpreter`: The interpreter to test with.
pub fn run_test(stream: &[u8], interpreter: &mut Interpreter<impl Handler + Clone>) -> Result<(), AmlError> {
    interpreter.load_table(stream)?;

    if let Some(result) = interpreter.evaluate_if_present(AmlName::from_str("\\MAIN").unwrap(), vec![])? {
        match *result {
            Object::Integer(0) => Ok(()),
            Object::Integer(other) => {
                error!("Test _MAIN returned non-zero exit code: {}", other);
                // TODO: wrong error - this should probs return a more complex err type
                Err(AmlError::NoCurrentOp)
            }
            _ => {
                error!("Test _MAIN returned unexpected object type: {}", *result);
                // TODO: wrong error
                Err(AmlError::NoCurrentOp)
            }
        }
    } else {
        Ok(())
    }
}
