//! A collection of helper utilities for testing AML using the [`acpi`] crate.
//!
//! These utilities are very heavily based on the way the [`acpi`] crate has used them historically.
//! As always, feel free to offer PRs for improvements.

pub mod handlers;

use acpi::{
    Handler,
    PhysicalMapping,
    address::MappedGas,
    aml::{AmlError, Interpreter, namespace::AmlName, object::Object},
};
use log::{error, trace};
use std::{
    ffi::OsStr,
    fmt::Debug,
    fs::File,
    io::{Read, Write},
    panic::{AssertUnwindSafe, catch_unwind},
    path::PathBuf,
    process::Command,
    ptr::NonNull,
    str::FromStr,
    sync::Arc,
};
use tempfile::{NamedTempFile, TempDir, tempdir};

/// The result of a call to [`run_test`]. This is a bit of a combination - it contains the actual
/// result of the test, but also the interpreter - if it is still valid.
pub enum RunTestResult<T>
where
    T: Handler,
{
    /// The test passed, and the interpreter is still valid.
    Pass(Interpreter<T>),

    /// The test failed, but the interpreter is still valid. A failure reason is also provided.
    Failed(Interpreter<T>, TestFailureReason),

    /// The test failed, and the interpreter is no longer valid.
    Panicked,
}

/// The result of a test
#[derive(Debug, PartialEq)]
pub enum TestResult {
    /// The test passed.
    Pass,

    /// The test failed.
    Failed(TestFailureReason),

    /// The test caused a panic, probably in the interpreter. This is separated out from the failed
    /// case for two reasons:
    ///
    /// 1. We want to highlight panics as they are in some ways worse than a failure - some AML
    ///    might cause the problems for the interpreter, but the system as a whole shouldn't crash
    /// 2. The interpreter that was being used for testing is no longer valid - a new one is needed.
    Panicked,
}

impl<T> From<&RunTestResult<T>> for TestResult
where
    T: Handler,
{
    fn from(result: &RunTestResult<T>) -> Self {
        match result {
            RunTestResult::Pass(_) => TestResult::Pass,
            RunTestResult::Failed(_, reason) => TestResult::Failed(reason.clone()),
            RunTestResult::Panicked => TestResult::Panicked,
        }
    }
}

/// Possible results of [`resolve_and_compile`].
pub enum CompilationOutcome {
    /// Not a valid ASL or AML file.
    Ignored,
    /// A filesystem error occurred.
    FilesystemErr(PathBuf),
    /// This file is already an AML file, does not need recompiling.
    IsAml(PathBuf),
    /// Both .asl and .aml files exist, and the .aml file is newer - it does not need recompiling.
    Newer(PathBuf),
    /// There's a .asl file only, but [`resolve_and_compile`] was called with `can_compile=false`.
    NotCompiled(PathBuf),
    /// Compilation was attempted but failed. The compilation output has been printed to stdout.
    Failed(PathBuf),
    /// An ASL file was found and compiled successfully. This variant contains the path to the
    /// compiled AML file.
    Succeeded(PathBuf),
}

/// Possible causes of a test failure.
#[derive(Clone, Debug, /*Eq, Hash,*/ PartialEq)]
pub enum TestFailureReason {
    /// The test ASL failed compilation by `iasl`.
    CompileFail,
    /// Some error occurred attempting to read or write the test file.
    FilesystemErr,
    /// Our interpreter failed to parse or execute the resulting AML.
    ParseFail(AmlError),
}

/// An internal-only struct that helps keep track of temporary files generated by
/// [`run_test_for_string`]
struct TempScriptFile {
    // This appears to be unused, but since it deletes the temporary directory when it's dropped, we
    // need to keep it.
    #[allow(unused)]
    dir: TempDir,
    asl_file: NamedTempFile,
}

/// Determine what to do with this file - ignore, compile and parse, or just parse.
/// If ".aml" does not exist, or if ".asl" is newer, compiles the file.
/// If the ".aml" file is newer, indicate it is ready to parse.
///
/// Arguments:
/// - `path`: The filename of an ASL file to (possibly) compile.
/// - `can_compile`: Whether compilation is allowed for this file. If not, any existing AML file
///   with the same name (but different extension) will be used.
pub fn resolve_and_compile(path: &PathBuf, can_compile: bool) -> CompilationOutcome {
    let Ok(meta) = path.metadata() else {
        return CompilationOutcome::FilesystemErr(path.clone());
    };

    // If this file is aml and it exists, it's ready for parsing
    // metadata() will error if the file does not exist
    if path.extension() == Some(OsStr::new("aml")) && meta.is_file() {
        return CompilationOutcome::IsAml(path.clone());
    }

    // If this file is not asl, it's not interesting. Error if the file does not exist.
    if path.extension() != Some(OsStr::new("asl")) || !meta.is_file() {
        return CompilationOutcome::Ignored;
    }

    let aml_path = path.with_extension("aml");
    if aml_path.is_file() {
        let Ok(asl_last_modified) = meta.modified() else {
            return CompilationOutcome::FilesystemErr(path.clone());
        };
        let Ok(aml_last_modified) = aml_path.metadata().and_then(|m| m.modified()) else {
            return CompilationOutcome::FilesystemErr(path.clone());
        };
        // If the aml is more recent than the asl, use the existing aml
        // Otherwise continue to compilation
        if asl_last_modified <= aml_last_modified {
            return CompilationOutcome::Newer(aml_path);
        }
    }

    if !can_compile {
        return CompilationOutcome::NotCompiled(path.clone());
    }

    // Compile the ASL file using `iasl`
    println!("Compiling file: {}", path.display());
    let output = Command::new("iasl").arg("-oa").arg(path).output();

    match output {
        Ok(output) => {
            if !output.status.success() {
                println!(
                    "Failed to compile ASL file: {}. Output from iasl:\n {}",
                    path.display(),
                    String::from_utf8_lossy(&output.stderr)
                );
                CompilationOutcome::Failed(path.clone())
            } else {
                CompilationOutcome::Succeeded(aml_path)
            }
        }
        Err(e) => {
            println!("Failed to compile ASL file: {}. Error: {}", path.display(), e);
            CompilationOutcome::Failed(path.clone())
        }
    }
}

/// Construct a new [interpreter](Interpreter) to use for testing.
///
/// This interpreter uses some simple fake registers and FACS to facilitate testing. It is not
/// mandatory to use this interpreter for testing when using other functions in this crate.
///
/// Arguments:
///
/// * `handler`: The Handler to be called by the interpreter when needed. This crate includes some
///   example [handlers].
pub fn new_interpreter<T>(handler: T) -> Interpreter<T>
where
    T: Handler + Clone,
{
    let fake_registers = Arc::new(acpi::registers::FixedRegisters {
        pm1_event_registers: acpi::registers::Pm1EventRegisterBlock {
            pm1_event_length: 8,
            pm1a: unsafe {
                MappedGas::map_gas(
                    acpi::address::GenericAddress {
                        address_space: acpi::address::AddressSpace::SystemIo,
                        bit_width: 32,
                        bit_offset: 0,
                        access_size: 1,
                        address: 0x400,
                    },
                    &handler,
                )
                .unwrap()
            },
            pm1b: None,
        },
        pm1_control_registers: acpi::registers::Pm1ControlRegisterBlock {
            pm1a: unsafe {
                MappedGas::map_gas(
                    acpi::address::GenericAddress {
                        address_space: acpi::address::AddressSpace::SystemIo,
                        bit_width: 32,
                        bit_offset: 0,
                        access_size: 1,
                        address: 0x600,
                    },
                    &handler,
                )
                .unwrap()
            },
            pm1b: None,
        },
    });

    // This PhysicalMapping is dropped when the interpreter is dropped, and if you use logging in
    // the handler object you'll see a call to Handler::unmap_physical_region without any
    // corresponding call to Interpreter::map_physical_region.
    let fake_facs = PhysicalMapping {
        physical_start: 0x0,
        virtual_start: NonNull::new(0x8000_0000_0000_0000 as *mut acpi::sdt::facs::Facs).unwrap(),
        region_length: 32,
        mapped_length: 32,
        handler: handler.clone(),
    };
    Interpreter::new(handler, 2, fake_registers, Some(fake_facs))
}

/// Test an ASL script given as a string, using [`run_test`].
///
/// Arguments:
/// * `asl`: A string slice containing an ASL script. This will be compiled to AML using `iasl` and
///   then tested using [`run_test`]
/// * `interpreter`: The interpreter to use for testing.
pub fn run_test_for_string<T>(asl: &'static str, interpreter: Interpreter<T>) -> RunTestResult<T>
where
    T: Handler,
{
    let script = create_script_file(asl);
    match resolve_and_compile(&script.asl_file.path().to_path_buf(), true) {
        CompilationOutcome::Succeeded(aml_path) | CompilationOutcome::IsAml(aml_path) => {
            run_test_for_file(&aml_path, interpreter)
        }
        _ => RunTestResult::Failed(interpreter, TestFailureReason::CompileFail),
    }
}

/// Test an AML file using [`run_test`]
///
/// Arguments:
///
/// * `file`: The path to the AML file to test. This must be an AML file otherwise the test will
///   fail very quickly.
/// * `interpreter`: The interpreter to use for testing.
pub fn run_test_for_file<T>(file: &PathBuf, interpreter: Interpreter<T>) -> RunTestResult<T>
where
    T: Handler,
{
    let Ok(mut file) = File::open(file) else {
        return RunTestResult::Failed(interpreter, TestFailureReason::FilesystemErr);
    };
    let mut contents = Vec::new();
    file.read_to_end(&mut contents).unwrap();

    const AML_TABLE_HEADER_LENGTH: usize = 36;
    let stream = &contents[AML_TABLE_HEADER_LENGTH..];

    run_test(stream, interpreter)
}

/// Internal function to create a temporary script file from an ASL string, plus to calculate the
/// name of the post-compilation AML file.
fn create_script_file(asl: &'static str) -> TempScriptFile {
    let dir = tempdir().unwrap();
    trace!("Created temp dir: {:?}", dir.path());
    let mut script_file = NamedTempFile::with_suffix_in(".asl", &dir).unwrap();
    trace!("Created temp file: {:?}", script_file.path());

    script_file.write_all(asl.as_bytes()).unwrap();
    script_file.flush().unwrap();

    TempScriptFile { dir, asl_file: script_file }
}

/// Run a test on an AML stream.
///
/// In this context, "a test" means:
///
/// * Attempting to parse the AML
/// * If the AML contains a "MAIN" method, attempting to execute it.
///
/// Arguments:
///
/// * `stream`: A slice containing the AML bytecode to test.
/// * `interpreter`: The interpreter to test with. The interpreter is consumed to maintain unwind
///   safety - if the interpreter panics, the caller should not be able to see the interpreter in
///   an inconsistent state.
pub fn run_test<T>(stream: &[u8], interpreter: Interpreter<T>) -> RunTestResult<T>
where
    T: Handler,
{
    // Without `AssertUnwindSafe`, the following code will not build as the Interpreter is not
    // unwind safe. To avoid the caller being able to see an inconsistent Interpreter, if a panic
    // occurs we drop the Interpreter, forcing the caller to create a new one.
    let result = catch_unwind(AssertUnwindSafe(|| -> Result<(), AmlError> {
        interpreter.load_table(stream)?;

        if let Some(result) = interpreter.evaluate_if_present(AmlName::from_str("\\MAIN").unwrap(), vec![])? {
            match *result {
                Object::Integer(0) => Ok(()),
                Object::Integer(other) => {
                    error!("Test _MAIN returned non-zero exit code: {}", other);
                    // TODO: wrong error - this should probs return a more complex err type
                    Err(AmlError::NoCurrentOp)
                }
                _ => {
                    error!("Test _MAIN returned unexpected object type: {}", *result);
                    // TODO: wrong error
                    Err(AmlError::NoCurrentOp)
                }
            }
        } else {
            Ok(())
        }
    }));

    match result {
        Ok(inner) => match inner {
            Ok(()) => RunTestResult::Pass(interpreter),
            Err(e) => RunTestResult::Failed(interpreter, TestFailureReason::ParseFail(e)),
        },
        Err(_e) => RunTestResult::Panicked,
    }
}
