//! Check that incorrect AML sequences in Match expressions appear to error correctly without panics

mod test_infra;

use crate::test_infra::run_opcodes_test_with_result;
use aml_test_tools::{RunTestResult, TestFailureReason, handlers::null_handler::NullHandler};
use std::assert_matches;

#[test]
fn invalid_arg_to_match() {
    // This AML is plausible looking but invalid - it attempts to pass Local0 instead of a match
    // operand.
    //
    // Generated by compiling the following script and changing the first Match Opcode:
    // ```
    // DefinitionBlock("", "DSDT", 1, "RSACPI", "MATCH", 1) {
    //     Name (AAAA, Package (4) { 0xAA, 0xAA})
    //
    //     Method (MAIN) {
    //         Local1 = Match (AAAA, MTR, 0, MGE, 2, 0)
    //         Return (0)
    //     }
    // }
    let opcodes = vec![
        0x08, // Name op
        0x41, 0x41, 0x41, 0x41, // "AAAA"
        0x12, // Package
        0x06, // 6 bytes long
        0x02, // 4 elements?
        0x0A, 0xAA, // Byte 0xAA
        0x0A, 0xAA, // Byte 0xAA
        0x70, // Store
        0x89, // Match
        0x41, 0x41, 0x41, 0x41, // "AAAA"
        0x68, // ** Invalid match opcode Arg0 **
        0x0A, 0x00, // Byte 0
        0x04, // Match Opcode
        0x0A, 0x02, // Byte 2 (operand)
        0x0A, 0x00, // Byte 0 (start offset)
        0x61, // Local1 - store target
        0xA4, 0x0A, 0x00, // Return byte 0
    ];

    let r = run_opcodes_test_with_result(&opcodes, NullHandler);
    assert_matches!(r, RunTestResult::Failed(_, TestFailureReason::ParseFail(_)))
}

#[test]
fn invalid_use_of_match_opcode() {
    let opcodes = vec![
        // Attempt something like `Local1 = MGT`
        0x70, 0x05, 0x61,
        // `Return (0)` (If the line above works, then 0 is returned and the test result is `Pass`,
        // rather than the `Failed` that we expect)
        0xA4, 0x0A, 0x00
    ];

    let r = run_opcodes_test_with_result(&opcodes, NullHandler);
    assert_matches!(r, RunTestResult::Failed(_, TestFailureReason::ParseFail(_)))
}