name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: x86_64-unknown-linux-gnu
            OS: ubuntu-latest
            FEATURES: ''
          - TARGET: aarch64-unknown-linux-gnu
            OS: ubuntu-latest
            FEATURES: '--no-default-features'
          - TARGET: i686-unknown-linux-gnu
            OS: ubuntu-latest
            FEATURES: '--no-default-features --features alloc'

    runs-on: ${{ matrix.OS }}
    env:
      TARGET: ${{ matrix.TARGET }}
      FEATURES: ${{ matrix.FEATURES }}

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'

    - name: Install Rust
      run: |
        rustup toolchain install --profile minimal --target ${{ matrix.target }} --component llvm-tools nightly
        rustup default nightly

    - name: Build crates
      run: cargo build --target $TARGET $FEATURES

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'
    - name: Install Rust
      run: |
        rustup toolchain install --profile minimal nightly
        rustup default nightly

    - name: Install dependencies
      run: sudo apt-get install -y acpica-tools

    - name: Run tests
      run: cargo test

    - name: Run AML test suite
      run: cargo run_tests -p tests

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'
    - name: Install Rust
      run: |
        rustup toolchain install --profile minimal --component clippy nightly
        rustup default nightly

    - name: Run clippy
      run: cargo clippy

    - name: Run clippy (tests)
      run: cargo clippy --tests

  test-no-alloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - name: Install Rust
        run: |
          rustup toolchain install --profile minimal --target x86_64-unknown-none --component llvm-tools nightly
          rustup default nightly

      - name: Build no alloc test exe
        working-directory: tools/no_alloc_check
        run: cargo build
